import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import test from "node:test";
import { closeEpisodeOversight } from "../src/prime-agent-plugin/extension-support/episode-close.ts";

function fixture(t){const cwd=realpathSync(mkdtempSync(join(tmpdir(),"pc-close-")));t.after(()=>rmSync(cwd,{recursive:true,force:true}));const slug="alpha",worktree=resolve(dirname(cwd),`${basename(cwd)}-${slug}-episode`),identity={version:2,slug,sourceLocation:`.ralph/plans/future/${slug}`,ownerSessionId:"owner",episodeId:"11111111-1111-4111-8111-111111111111",episodeActiveSessionId:"route",episodeSessionFile:join(worktree,"episode.jsonl"),branch:`episode/${slug}`,worktree,sessionName:`${slug}-episode`,bootstrapAdmission:"delivered"},root=join(cwd,".prime/agent/state/spec-episodes"),path=join(root,`${slug}.json`);mkdirSync(root,{recursive:true});writeFileSync(path,JSON.stringify(identity));const marker={markerVersion:2,status:"active",ownerSessionId:identity.ownerSessionId,slug,sourceLocation:identity.sourceLocation,episodeId:identity.episodeId,episodeSessionFile:identity.episodeSessionFile,branch:identity.branch,worktree:identity.worktree,sessionName:identity.sessionName,identityVersion:2,admission:"delivered"},ctx={cwd,sessionManager:{getSessionId(){return"owner"}}};return{cwd,path,identity,marker,ctx}}
test("close removes only matching identity and appends inactive evidence",t=>{const f=fixture(t),kept=join(dirname(f.path),"unrelated.txt");writeFileSync(kept,"keep");const appended=[];const result=closeEpisodeOversight(f.identity.sourceLocation,f.ctx,f.marker,m=>appended.push({...m,status:"inactive"}));assert.equal(result.reused,false);assert.equal(existsSync(f.path),false);assert.equal(readFileSync(kept,"utf8"),"keep");assert.equal(appended.length,1);assert.equal(appended[0].status,"inactive")});
test("identical replay is idempotent and appends no duplicate evidence",t=>{const f=fixture(t);rmSync(f.path);const appended=[];const result=closeEpisodeOversight(f.identity.sourceLocation,f.ctx,{...f.marker,status:"inactive"},m=>appended.push(m));assert.equal(result.reused,true);assert.equal(appended.length,0)});
test("owner location and identity mismatch block without mutation",t=>{for(const mode of ["owner","location","identity"]){const f=fixture(t),appended=[];if(mode==="owner")f.ctx.sessionManager.getSessionId=()=>"other";if(mode==="identity"){const value=JSON.parse(readFileSync(f.path,"utf8"));value.episodeId="different";writeFileSync(f.path,JSON.stringify(value))}const location=mode==="location"?".ralph/plans/future/beta":f.identity.sourceLocation;assert.throws(()=>closeEpisodeOversight(location,f.ctx,f.marker,m=>appended.push(m)),/owner mismatch|location does not match|does not match exact/);assert.equal(existsSync(f.path),true);assert.equal(appended.length,0)}});
test("unsafe identity path blocks",t=>{const f=fixture(t),target=join(f.cwd,"target.json");writeFileSync(target,readFileSync(f.path));rmSync(f.path);symlinkSync(target,f.path);assert.throws(()=>closeEpisodeOversight(f.identity.sourceLocation,f.ctx,f.marker,()=>{}),/not a regular file/);assert.equal(existsSync(target),true)});

test("append failure leaves original active state retryable",t=>{const f=fixture(t);assert.throws(()=>closeEpisodeOversight(f.identity.sourceLocation,f.ctx,f.marker,()=>{throw Error("append failed")}),/append failed/);assert.equal(existsSync(f.path),true)});
test("remove failure leaves inactive evidence and exact replay completes without duplication",t=>{const f=fixture(t),appended=[];assert.throws(()=>closeEpisodeOversight(f.identity.sourceLocation,f.ctx,f.marker,m=>appended.push({...m,status:"inactive"}),()=>{throw Error("remove failed")}),/remove failed/);assert.equal(existsSync(f.path),true);assert.equal(appended.length,1);const result=closeEpisodeOversight(f.identity.sourceLocation,f.ctx,{...f.marker,status:"inactive"},m=>appended.push(m));assert.equal(result.reused,false);assert.equal(existsSync(f.path),false);assert.equal(appended.length,1)});
test("old inactive replay cannot clear a newer same-location generation",t=>{const f=fixture(t),old={...f.marker,status:"inactive",episodeId:"old-generation"};assert.throws(()=>closeEpisodeOversight(f.identity.sourceLocation,f.ctx,old,()=>{}),/does not match exact/);assert.equal(existsSync(f.path),true)});

test("broken identity symlink is never treated as an idempotent absence",t=>{const f=fixture(t);rmSync(f.path);symlinkSync(join(f.cwd,"missing-target"),f.path);assert.throws(()=>closeEpisodeOversight(f.identity.sourceLocation,f.ctx,{...f.marker,status:"inactive"},()=>{}),/not a regular file/)});
