import assert from "node:assert/strict";import test from "node:test";
import {authorizeEpisodeFinalization,completeEpisodeFinalization}from"../src/prime-agent-plugin/extension-support/episode-finalization.ts";
const LOCATION=".ralph/plans/future/alpha";
function fixture({owner="owner",live=false,worktree=false,merged=true,failRemove=false}={}){const repo="/repo",identityPath="/repo/.prime/agent/state/spec-episodes/alpha.json",receiptPath="/repo/.prime/agent/state/spec-episodes/alpha.finalization.json";const files=new Map();const record={version:2,slug:"alpha",sourceLocation:LOCATION,ownerSessionId:owner,episodeId:"episode",episodeActiveSessionId:"route",episodeSessionFile:"/sessions/episode.jsonl",branch:"episode/alpha",worktree:"/worktree",sessionName:"alpha-episode",bootstrapAdmission:"delivered"};files.set(identityPath,record);const removed=[];let closed=0;const deps={async listSessions(){return live?[{sessionId:"episode",sessionFile:"/sessions/episode.jsonl",activeSessionId:"route",isSessionActive:true}]:[]},close(){closed++},repositoryRoot(){return repo},worktrees(){return worktree?[{path:"/worktree",branch:"episode/alpha"}]:[]},revParse(_repo,ref){return ref==="episode/alpha"?"episode-tip":"head"},isAncestor(){return merged},exists(path){return path==="/worktree"?worktree:files.has(path)},readJson(path){if(!files.has(path))throw Error("missing "+path);return structuredClone(files.get(path))},writeJson(path,value){files.set(path,structuredClone(value))},remove(path){if(failRemove&&path===receiptPath)throw Error("remove failed");files.delete(path);removed.push(path)}};const ctx={cwd:repo,sessionManager:{getSessionId(){return"owner"}}};return{repo,identityPath,receiptPath,record,files,removed,deps,ctx,get closed(){return closed}}}

test("authorize confirms once, persists exact receipt, and replay is side-effect free",async()=>{const f=fixture();let confirms=0;const confirm=async()=>{confirms++;return true};const first=await authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,confirm,f.deps);assert.equal(first.reused,false);assert.equal(confirms,1);assert.equal(f.files.get(f.receiptPath).episodeCommit,"episode-tip");assert.equal(f.files.has(f.identityPath),true);assert.equal(f.removed.length,0);const replay=await authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,confirm,f.deps);assert.equal(replay.reused,true);assert.equal(confirms,1)});

test("authorize rejects owner, location, disposition, cancellation, and conflicting replay",async()=>{const wrong=fixture({owner:"other"});await assert.rejects(authorizeEpisodeFinalization(LOCATION,"merged",wrong.ctx,async()=>true,wrong.deps),/owner mismatch/);const f=fixture();await assert.rejects(authorizeEpisodeFinalization("bad","merged",f.ctx,async()=>true,f.deps),/Invalid/);await assert.rejects(authorizeEpisodeFinalization(LOCATION,"paused",f.ctx,async()=>true,f.deps),/Disposition/);await assert.rejects(authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,async()=>false,f.deps),/cancelled/);await authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,async()=>true,f.deps);await assert.rejects(authorizeEpisodeFinalization(LOCATION,"abandoned",f.ctx,async()=>true,f.deps),/different terminal/)});

test("complete refuses premature or ambiguous terminal facts and preserves state",async()=>{for(const options of [{live:true},{worktree:true},{merged:false}]){const f=fixture(options);await authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,async()=>true,f.deps);const marker={version:1,status:"active",ownerSessionId:"owner",sourceLocation:LOCATION,slug:"alpha",episodeId:"episode",episodeSessionFile:"/sessions/episode.jsonl"};await assert.rejects(completeEpisodeFinalization(LOCATION,"merged",f.ctx,()=>{},marker,f.deps));assert.equal(f.files.has(f.identityPath),true);assert.equal(f.files.has(f.receiptPath),true)}});

test("successful complete appends inactive and clears only matching state",async()=>{const f=fixture();f.files.set("/unrelated",{keep:true});await authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,async()=>true,f.deps);const marker={version:1,status:"active",ownerSessionId:"owner",sourceLocation:LOCATION,slug:"alpha",episodeId:"episode",episodeSessionFile:"/sessions/episode.jsonl"};const transitions=[];await completeEpisodeFinalization(LOCATION,"merged",f.ctx,(status)=>transitions.push(status),marker,f.deps);assert.deepEqual(transitions,["inactive"]);assert.equal(f.files.has(f.identityPath),false);assert.equal(f.files.has(f.receiptPath),false);assert.deepEqual(f.files.get("/unrelated"),{keep:true})});

test("abandoned completion requires the authorized commit to remain unmerged",async()=>{const f=fixture({merged:false});await authorizeEpisodeFinalization(LOCATION,"abandoned",f.ctx,async()=>true,f.deps);const marker={version:1,status:"active",ownerSessionId:"owner",sourceLocation:LOCATION,slug:"alpha",episodeId:"episode",episodeSessionFile:"/sessions/episode.jsonl"};const transitions=[];await completeEpisodeFinalization(LOCATION,"abandoned",f.ctx,(status)=>transitions.push(status),marker,f.deps);assert.deepEqual(transitions,["inactive"]);assert.equal(f.files.has(f.identityPath),false)});

test("clear failure restores receipt, identity, and active transition",async()=>{const f=fixture({failRemove:true});await authorizeEpisodeFinalization(LOCATION,"merged",f.ctx,async()=>true,f.deps);const marker={version:1,status:"active",ownerSessionId:"owner",sourceLocation:LOCATION,slug:"alpha",episodeId:"episode",episodeSessionFile:"/sessions/episode.jsonl"};const transitions=[];await assert.rejects(completeEpisodeFinalization(LOCATION,"merged",f.ctx,(status)=>transitions.push(status),marker,f.deps),/active state was restored/);assert.deepEqual(transitions,["inactive","active"]);assert.equal(f.files.has(f.identityPath),true);assert.equal(f.files.has(f.receiptPath),true)});
