import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import test from "node:test";
import {
  appendActiveOversight, applyConversationContext, assertConversationPromotionReady,
  EXPECTED_IDENTITY_KERNEL_BLOCK, OVERSIGHT_MARKER_TYPE, OVERSIGHT_PACKAGE_TYPE,
  registerConversationOversight, currentOversightMarkerForClose,
} from "../src/prime-agent-plugin/extension-support/conversation-oversight.ts";

function fixture(t,{sessionId="owner",prompt=EXPECTED_IDENTITY_KERNEL_BLOCK,entries=[]}={}){
  const cwd=realpathSync(mkdtempSync(join(tmpdir(),"pc-oversight-")));t.after(()=>rmSync(cwd,{recursive:true,force:true}));
  const packagePath=join(cwd,".ralph/skills/oversee-episode/SKILL.md");mkdirSync(dirname(packagePath),{recursive:true});
  writeFileSync(packagePath,"---\nname: oversee-episode\ndescription: test package\n---\nREVISION ONE");
  const branch=structuredClone(entries),events=new Map(),notifications=[];let aborts=0,currentPrompt=prompt;
  const ctx={cwd,ui:{notify(message,level){notifications.push({message,level})}},abort(){aborts++},getSystemPrompt(){return currentPrompt},sessionManager:{getSessionId(){return sessionId},getBranch(){return branch}}};
  const pi={on(name,handler){events.set(name,handler)},appendEntry(customType,data){branch.push({type:"custom",customType,data})},sendMessage(message){branch.push({type:"custom_message",...message})}};
  registerConversationOversight(pi);return{cwd,packagePath,branch,events,notifications,get aborts(){return aborts},setPrompt(value){currentPrompt=value},ctx,pi};
}
function identity(f,{episodeId="11111111-1111-4111-8111-111111111111",slug="alpha",owner=f.ctx.sessionManager.getSessionId(),admission="delivered"}={}){
  const worktree=resolve(dirname(f.cwd),`${basename(f.cwd)}-${slug}-episode`),value={version:2,slug,sourceLocation:`.ralph/plans/future/${slug}`,ownerSessionId:owner,episodeId,episodeActiveSessionId:"active",episodeSessionFile:join(worktree,"episode.jsonl"),branch:`episode/${slug}`,worktree,sessionName:`${slug}-episode`,bootstrapAdmission:admission};
  const path=join(f.cwd,".prime/agent/state/spec-episodes",`${slug}.json`);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(value));return{...value,reused:false};
}
function marker(value,status="active"){return{markerVersion:2,status,ownerSessionId:value.ownerSessionId,slug:value.slug,sourceLocation:value.sourceLocation,episodeId:value.episodeId,episodeSessionFile:value.episodeSessionFile,branch:value.branch,worktree:value.worktree,sessionName:value.sessionName,identityVersion:value.version,admission:value.bootstrapAdmission};}
function context(f,messages=[]){return f.events.get("context")({messages},f.ctx);}

test("managed kernel source equals the canonical expected block",()=>{assert.equal(readFileSync(new URL("../src/prime-agent-plugin/APPEND_SYSTEM.md",import.meta.url),"utf8").trim(),EXPECTED_IDENTITY_KERNEL_BLOCK)});
test("registers only session recovery and context hooks",()=>{const events=new Map();registerConversationOversight({on(n,h){events.set(n,h)},appendEntry(){}});assert.deepEqual([...events.keys()],["session_start","context"])});
test("truly inactive conversation tolerates project or CLI kernel shadowing",t=>{for(const prompt of ["BASE","CLI SHADOW"]){const f=fixture(t,{prompt});assert.deepEqual(context(f,[{role:"user",content:"hello"}]),{messages:[{role:"user",content:"hello"}]});assert.equal(f.aborts,0)}});
test("promotion requires the canonical kernel and package",t=>{const f=fixture(t);assert.doesNotThrow(()=>appendActiveOversight(f.pi,f.ctx,identity(f)));for(const prompt of ["PRIME_CLAW_CONVERSATION_IDENTITY_V1",`${EXPECTED_IDENTITY_KERNEL_BLOCK}\n${EXPECTED_IDENTITY_KERNEL_BLOCK}`]){const bad=fixture(t,{prompt});assert.throws(()=>appendActiveOversight(bad.pi,bad.ctx,identity(bad)),/intact managed identity kernel/)}const bad=fixture(t);writeFileSync(bad.packagePath,"---\nname: wrong\ndescription: x\n---\nbody");assert.throws(()=>appendActiveOversight(bad.pi,bad.ctx,identity(bad)),/requires exact name/)});
test("active exact expectation injects one freshly read canonical package",t=>{const f=fixture(t),episode=identity(f);appendActiveOversight(f.pi,f.ctx,episode);let result=context(f,[{role:"user",content:"x"}]);assert.equal(result.messages.filter(x=>x.customType===OVERSIGHT_PACKAGE_TYPE).length,1);writeFileSync(f.packagePath,"---\nname: oversee-episode\ndescription: changed\n---\nREVISION TWO");result=context(f,result.messages);const packages=result.messages.filter(x=>x.customType===OVERSIGHT_PACKAGE_TYPE);assert.equal(packages.length,1);assert.match(packages[0].content,/REVISION TWO/);assert.equal(currentOversightMarkerForClose(f.ctx,episode.sourceLocation).episodeId,episode.episodeId)});
test("session start reconstructs a missing active marker from exact expectation",async t=>{const f=fixture(t),episode=identity(f);await f.events.get("session_start")({},f.ctx);assert.equal(f.branch.findLast(x=>x.customType===OVERSIGHT_MARKER_TYPE).data.status,"active");assert.equal(f.branch.findLast(x=>x.customType===OVERSIGHT_MARKER_TYPE).data.episodeId,episode.episodeId);assert.match(f.notifications.at(-1).message,/Recovered active oversight/)});
test("inactive closed evidence is ordinary and allows a later episode",t=>{const f=fixture(t);const old={version:2,slug:"alpha",sourceLocation:".ralph/plans/future/alpha",ownerSessionId:"owner",episodeId:"old",episodeActiveSessionId:"route",episodeSessionFile:"/old/session.jsonl",branch:"episode/alpha",worktree:"/old/worktree",sessionName:"alpha-episode",bootstrapAdmission:"delivered"};f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker(old,"inactive")});assert.deepEqual(context(f),{messages:[]});assert.doesNotThrow(()=>assertConversationPromotionReady(f.ctx,".ralph/plans/future/beta"));const beta=identity(f,{slug:"beta",episodeId:"new"});appendActiveOversight(f.pi,f.ctx,beta);assert.equal(currentOversightMarkerForClose(f.ctx,beta.sourceLocation).episodeId,"new")});
test("orphan active exact-owner evidence blocks instead of becoming ordinary",t=>{const f=fixture(t);const old={version:2,slug:"alpha",sourceLocation:".ralph/plans/future/alpha",ownerSessionId:"owner",episodeId:"old",episodeActiveSessionId:"route",episodeSessionFile:"/old/session.jsonl",branch:"episode/alpha",worktree:"/old/worktree",sessionName:"alpha-episode",bootstrapAdmission:"delivered"};f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker(old)});assert.throws(()=>context(f),/orphan active/);assert.equal(f.aborts,1)});
test("foreign owner evidence is inert",t=>{const foreign={version:2,slug:"alpha",sourceLocation:".ralph/plans/future/alpha",ownerSessionId:"other",episodeId:"foreign",episodeActiveSessionId:"route",episodeSessionFile:"/old/session.jsonl",branch:"episode/alpha",worktree:"/old/worktree",sessionName:"alpha-episode",bootstrapAdmission:"delivered"};const f=fixture(t,{entries:[{type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker(foreign)}]});assert.deepEqual(context(f),{messages:[]})});
test("unclassifiable owner and stable-binding mismatch fail closed",t=>{const f=fixture(t),episode=identity(f);f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:{...marker(episode),ownerSessionId:""}});assert.throws(()=>context(f),/owner is unclassifiable/);const g=fixture(t),other=identity(g);g.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:{...marker(other),branch:"episode/wrong"}});assert.throws(()=>context(g),/corrupt|disagrees/)});
test("bounded EPISODE identity overrides conversation ownership",t=>{const f=fixture(t);f.branch.push({type:"custom",customType:"prime-claw-bounded-identity",data:{version:1,role:"EPISODE",sessionId:"owner"}});const result=context(f);assert.equal(result.messages.at(-1).customType,"prime-claw-bounded-identity-package");assert.match(result.messages.at(-1).content,/role=EPISODE/)});

test("inactive marker with exact identity remains provider-visible for explicit close replay",t=>{const f=fixture(t),episode=identity(f);f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker(episode,"inactive")});const result=context(f);assert.equal(result.messages.filter(x=>x.customType===OVERSIGHT_PACKAGE_TYPE).length,1);assert.equal(currentOversightMarkerForClose(f.ctx,episode.sourceLocation).status,"inactive")});

test("closed future-folder locations cannot be reused for a later generation",t=>{const f=fixture(t);const old={version:2,slug:"alpha",sourceLocation:".ralph/plans/future/alpha",ownerSessionId:"owner",episodeId:"old",episodeActiveSessionId:"route",episodeSessionFile:"/old/session.jsonl",branch:"episode/alpha",worktree:"/old/worktree",sessionName:"alpha-episode",bootstrapAdmission:"delivered"};f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker(old,"inactive")});assert.throws(()=>assertConversationPromotionReady(f.ctx,old.sourceLocation),/cannot be reused/);assert.doesNotThrow(()=>assertConversationPromotionReady(f.ctx,".ralph/plans/future/beta"))});
test("duplicate generations at one location block close lookup",t=>{const f=fixture(t),current=identity(f);f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker(current)});f.branch.push({type:"custom",customType:OVERSIGHT_MARKER_TYPE,data:marker({...current,episodeId:"older"},"inactive")});assert.throws(()=>currentOversightMarkerForClose(f.ctx,current.sourceLocation),/multiple oversight generations/)});
