import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { reconcilePrimeClawProject } from "../src/prime-agent-plugin/extension-support/project-initialization.ts";
import { requestTemplateReview,startTemplateReview,finishTemplateReview,recoverTemplateReview } from "../src/prime-agent-plugin/extension-support/template-review.ts";
const PLUGIN=resolve("src/prime-agent-plugin");
function git(cwd,...args){return execFileSync("git",["-C",cwd,...args],{encoding:"utf8"})}
class Runner { constructor(){this.registrations=[];this.failDiff=false;this.diffs=0} run(command,args,options={}){if(command==="git"){try{return{stdout:execFileSync(command,args,{cwd:options.cwd,encoding:"utf8",stdio:["ignore","pipe","pipe"]}),stderr:"",status:0}}catch(e){const r={stdout:String(e.stdout??""),stderr:String(e.stderr??e.message),status:Number.isInteger(e.status)?e.status:1};if(!options.allowFailure)throw e;return r}} if(command==="orca"&&args[0]==="file"){this.diffs++;return this.failDiff?{stdout:"",stderr:"unavailable",status:1}:{stdout:JSON.stringify({opened:true}),stderr:"",status:0}} if(command==="orca"&&args[1]==="list")return{stdout:JSON.stringify({result:{repos:this.registrations}}),stderr:"",status:0};if(command==="orca"&&args[1]==="add")return{stdout:"{}",stderr:"",status:0};throw Error(`unexpected ${command} ${args}`)}}
function fixture(t){const root=join(mkdtempSync(join(tmpdir(),"pc-review-")),"repo");mkdirSync(root);git(root,"init","-q","-b","main");git(root,"config","user.name","Test");git(root,"config","user.email","test@example.invalid");writeFileSync(join(root,"README.md"),"x\n");git(root,"add","README.md");git(root,"commit","-qm","init");const runner=new Runner();reconcilePrimeClawProject({cwd:root,pluginRoot:PLUGIN,home:dirname(root),runner});git(root,"add",".");git(root,"commit","-qm","initialize");const rel=".agents/skills/prepare/SKILL.md",path=join(root,rel);writeFileSync(path,readFileSync(path,"utf8")+"\ncommitted customization\n");git(root,"add",rel);git(root,"commit","-qm","customize");return{root,runner,rel,path,custom:readFileSync(path,"utf8"),upstream:readFileSync(join(PLUGIN,"skills/project-templates/prepare.md"),"utf8")}}

test("request/cancel-before-ready is a no-op and start holds until visible completion",t=>{const f=fixture(t);const req=requestTemplateReview(f.root,"project-skill-prepare",{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner});assert.match(req.message,/temporarily overwrite/);assert.equal(readFileSync(f.path,"utf8"),f.custom);assert.equal(f.runner.diffs,0);const early=finishTemplateReview(f.root,"cancel",false,{home:dirname(f.root),runner:f.runner});assert.equal(early.noOp,true);assert.throws(()=>startTemplateReview(f.root,"project-skill-prepare",false,{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner}),/explicit ready/);assert.equal(readFileSync(f.path,"utf8"),f.custom);const started=startTemplateReview(f.root,"project-skill-prepare",true,{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner});assert.equal(started.held,true);assert.equal(readFileSync(f.path,"utf8"),f.upstream);assert.ok(existsSync(join(f.root,".prime-claw/template-review.json")));assert.throws(()=>recoverTemplateReview(f.root,"keep",{home:dirname(f.root),runner:f.runner}),/normal held review/);assert.throws(()=>finishTemplateReview(f.root,"complete",false,{home:dirname(f.root),runner:f.runner}),/visible/);assert.equal(readFileSync(f.path,"utf8"),f.upstream);const done=finishTemplateReview(f.root,"complete",true,{home:dirname(f.root),runner:f.runner});assert.equal(done.clean,true);assert.equal(readFileSync(f.path,"utf8"),f.custom);assert.equal(git(f.root,"status","--porcelain","--",f.rel),"")});

test("dirty path is refused and Orca error falls back without leaving overwrite",t=>{const f=fixture(t);writeFileSync(f.path,f.custom+"dirty\n");assert.throws(()=>startTemplateReview(f.root,"project-skill-prepare",true,{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner}),/staged or unstaged/);git(f.root,"restore","--worktree","--",f.rel);f.runner.failDiff=true;const result=startTemplateReview(f.root,"project-skill-prepare",true,{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner});assert.equal(result.held,false);assert.equal(result.restored,true);assert.equal(result.fallback,"git-diff");assert.match(result.diff,/committed customization/);assert.equal(readFileSync(f.path,"utf8"),f.custom);assert.equal(existsSync(join(f.root,".prime-claw/template-review.json")),false)});

test("interruption preserves changed bytes and requires explicit recovery",t=>{const f=fixture(t);startTemplateReview(f.root,"project-skill-prepare",true,{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner});writeFileSync(f.path,"operator edited held bytes\n");assert.throws(()=>finishTemplateReview(f.root,"cancel",false,{home:dirname(f.root),runner:f.runner}),/preserved/);assert.equal(readFileSync(f.path,"utf8"),"operator edited held bytes\n");assert.ok(existsSync(join(f.root,".prime-claw/template-review.json")));const restored=recoverTemplateReview(f.root,"restore",{home:dirname(f.root),runner:f.runner});assert.equal(restored.clean,true);assert.equal(readFileSync(f.path,"utf8"),f.custom)});

test("explicit keep preserves interrupted bytes without staging or committing",t=>{const f=fixture(t);startTemplateReview(f.root,"project-skill-prepare",true,{pluginRoot:PLUGIN,home:dirname(f.root),runner:f.runner});writeFileSync(f.path,"keep me\n");assert.throws(()=>finishTemplateReview(f.root,"cancel",false,{home:dirname(f.root),runner:f.runner}));const kept=recoverTemplateReview(f.root,"keep",{home:dirname(f.root),runner:f.runner});assert.equal(kept.kept,true);assert.equal(readFileSync(f.path,"utf8"),"keep me\n");assert.match(git(f.root,"status","--porcelain","--",f.rel),/^ M /)});
