import json
import shutil
import subprocess
from pathlib import Path

REPO=Path(__file__).resolve().parents[1]
PRIME=shutil.which("prime-agent")
EXT=REPO/"src/prime-agent-plugin/extensions/project-conversation.ts"
KERNEL=REPO/"src/prime-agent-plugin/APPEND_SYSTEM.md"
SKILL=REPO/".ralph/skills/oversee-episode/SKILL.md"

def _outer_provider(path:Path):
 path.write_text(r"""import {createAssistantMessageEventStream}from"@earendil-works/pi-ai";export default function p(pi){pi.registerProvider("outer",{baseUrl:"x",apiKey:"x",api:"outer",streamSimple(model){const s=createAssistantMessageEventStream();queueMicrotask(()=>{const m={role:"assistant",content:[{type:"text",text:"ok"}],api:model.api,provider:model.provider,model:model.id,usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:"stop",timestamp:Date.now()};s.push({type:"start",partial:m});s.push({type:"done",reason:"stop",message:m});s.end()});return s},models:[{id:"m",name:"M",reasoning:false,input:["text"],cost:{input:0,output:0,cacheRead:0,cacheWrite:0},contextWindow:10000,maxTokens:1000}]})}""")

def test_native_run_paths_and_real_child_precedence(tmp_path):
 assert PRIME
 project=tmp_path/"project";(project/".prime/agent").mkdir(parents=True);(project/".prime/agent/APPEND_SYSTEM.md").write_text(KERNEL.read_text());skill=project/".ralph/skills/oversee-episode/SKILL.md";skill.parent.mkdir(parents=True);skill.write_text(SKILL.read_text())
 agent=tmp_path/"agent";agent.mkdir();records=tmp_path/"records.jsonl";result=tmp_path/"result.json"
 provider=tmp_path/"provider.ts";provider.write_text(rf"""import {{appendFileSync}}from"node:fs";import{{createAssistantMessageEventStream}}from"@earendil-works/pi-ai";const p={json.dumps(str(records))};let tool=false;function rec(x){{appendFileSync(p,JSON.stringify(x)+"\n")}}function msg(model,c,reason="stop"){{return{{role:"assistant",content:c,api:model.api,provider:model.provider,model:model.id,usage:{{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}}}},stopReason:reason,timestamp:Date.now()}}}}export default function x(pi){{pi.registerCommand("custom",{{description:"poc",handler:async()=>pi.sendMessage({{customType:"poc",content:"CUSTOM",display:true}},{{triggerTurn:true}})}});pi.registerTool({{name:"poc_tool",label:"POC",description:"poc",executionMode:"sequential",parameters:{{type:"object",properties:{{}},additionalProperties:false}},async execute(){{return{{content:[{{type:"text",text:"ok"}}],details:{{}}}}}}}});pi.registerProvider("poc",{{baseUrl:"x",apiKey:"x",api:"poc",streamSimple(model,context){{const all=JSON.stringify(context.messages??[]);rec({{kind:"provider",kernel:context.systemPrompt.split("PRIME_CLAW_CONVERSATION_IDENTITY_V1").length-1,package:all.split("name: oversee-episode").length-1,depth1:context.systemPrompt.includes("Recursive agent depth: 1"),tail:all.slice(-120)}});const s=createAssistantMessageEventStream();const done=()=>{{if(all.includes("TOOL")&&!tool){{tool=true;const tc={{type:"toolCall",id:"t",name:"poc_tool",arguments:{{}}}},m=msg(model,[tc],"toolUse");s.push({{type:"start",partial:m}});s.push({{type:"toolcall_start",contentIndex:0,partial:m}});s.push({{type:"toolcall_end",contentIndex:0,toolCall:tc,partial:m}});s.push({{type:"done",reason:"toolUse",message:m}});s.end();return}}const m=msg(model,[{{type:"text",text:"ok"}}]);s.push({{type:"start",partial:m}});s.push({{type:"done",reason:"stop",message:m}});s.end()}};if(all.includes("HOLD"))setTimeout(done,250);else queueMicrotask(done);return s}},models:[{{id:"m",name:"M",reasoning:false,input:["text"],cost:{{input:0,output:0,cacheRead:0,cacheWrite:0}},contextWindow:100000,maxTokens:1000}}]}})}}""")
 setup=tmp_path/"setup.ts";setup.write_text(rf"""import{{mkdirSync,writeFileSync}}from"node:fs";import{{dirname,join}}from"node:path";export default function s(pi){{pi.on("session_start",(_e,ctx)=>{{if(ctx.getSystemPrompt().includes("Recursive agent depth: 1"))return;const id=ctx.sessionManager.getSessionId(),slug="alpha",sessionFile=join(ctx.cwd,"episode.jsonl"),path=join(ctx.cwd,".prime/agent/state/spec-episodes/alpha.json");mkdirSync(dirname(path),{{recursive:true}});writeFileSync(path,JSON.stringify({{version:2,slug,sourceLocation:".ralph/plans/future/alpha",ownerSessionId:id,episodeId:"episode",episodeActiveSessionId:"active",episodeSessionFile:sessionFile,branch:"episode/alpha",worktree:join(ctx.cwd,"worktree"),sessionName:"alpha-episode",bootstrapAdmission:"delivered"}}));pi.appendEntry("prime-claw-conversation-oversight",{{version:1,status:"active",ownerSessionId:id,sourceLocation:".ralph/plans/future/alpha",slug,episodeId:"episode",episodeSessionFile:sessionFile}})}})}}""")
 driver=tmp_path/"driver.ts";driver.write_text(rf"""import{{writeFileSync}}from"node:fs";import{{join}}from"node:path";import{{createAgentSessionRuntime,createAgentSessionServices,createAgentSessionFromServices,SessionManager}}from"@earendil-works/pi-coding-agent";const cwd={json.dumps(str(project))},agentDir={json.dumps(str(agent))},provider={json.dumps(str(provider))},setup={json.dumps(str(setup))},ext={json.dumps(str(EXT))},result={json.dumps(str(result))};const delay=ms=>new Promise(r=>setTimeout(r,ms));export default function d(pi){{pi.on("session_start",async()=>{{let runtime;try{{const make=async target=>{{const services=await createAgentSessionServices({{cwd:target.cwd,agentDir,noBuiltinHerdrReporter:true,telemetryDisabled:true,resourceLoaderOptions:{{additionalExtensionPaths:[provider,setup,ext],noExtensions:true,noSkills:true,noPromptTemplates:true,noContextFiles:true,noThemes:true}}}});const model=services.modelRegistry.find("poc","m");const made=await createAgentSessionFromServices({{services,sessionManager:target.sessionManager,sessionStartEvent:target.sessionStartEvent,model,thinkingLevel:"off",noTools:false,prewarmIpythonKernel:false,telemetryDisabled:true,...(target.sessionOptions??{{}})}});return{{...made,services,diagnostics:services.diagnostics}}}};runtime=await createAgentSessionRuntime(make,{{cwd,agentDir,sessionManager:SessionManager.inMemory(cwd)}});await runtime.session.bindExtensions({{}});await runtime.session.prompt("NORMAL");await runtime.session.prompt("/custom");await runtime.session.promptHeartbeat({{id:"hb",schedule:{{expression:"*/15 * * * *"}},runCount:1,status:"running",prompt:"HEARTBEAT"}});await runtime.session.acceptAgentMessagePrompt("AGENT_MESSAGE");await runtime.session.waitForSessionInputIdle();const held=runtime.session.prompt("HOLD");await delay(30);await runtime.session.followUp("FOLLOWUP");await held;await runtime.session.waitForSessionInputIdle();const held2=runtime.session.prompt("HOLD CANCEL");await delay(30);await runtime.session.followUp("CANCELLED");runtime.session.clearQueue();await held2;await runtime.session.waitForSessionInputIdle();await runtime.session.prompt("TOOL");const child=await runtime.createRlmSubagentRuntime({{id:"child",sessionName:"EXPERT",parentSession:runtime.session,sessionDir:join(agentDir,"child"),model:runtime.session.model,thinkingLevel:"off",scopedModels:[],activeToolNames:[],allowedToolNames:[],customTools:[],includeGoals:false,includeCompactSkill:false,rlmDepth:1,rlmMaxDepth:2,prompt:"bounded"}});await child.session.prompt("CHILD");writeFileSync(result,JSON.stringify({{ok:true}}))}}catch(e){{writeFileSync(result,JSON.stringify({{error:String(e),stack:e?.stack}}))}}finally{{await runtime?.dispose()}}}})}}""")
 outer=tmp_path/"outer.ts";_outer_provider(outer)
 cp=subprocess.run([PRIME,"--mode","text","--offline","--no-session","--no-skills","--no-prompt-templates","--no-context-files","--no-extensions","--cwd",str(project),"-e",str(outer),"-e",str(driver),"--provider","outer","--model","m","-p","outer"],cwd=REPO,capture_output=True,text=True,timeout=30)
 assert cp.returncode==0,cp.stdout+cp.stderr
 assert json.loads(result.read_text())=={"ok":True}
 rows=[json.loads(x) for x in records.read_text().splitlines()]
 parent=[r for r in rows if not r["depth1"]];child=[r for r in rows if r["depth1"]]
 assert len(parent)>=8
 assert all(r["kernel"]==1 and r["package"]==1 for r in parent)
 assert len(child)==1 and child[0]["kernel"]==1 and child[0]["package"]==0
 assert not any("CANCELLED" in r["tail"] for r in rows)


def test_native_auto_compaction_restores_first_real_active_call(tmp_path):
    assert PRIME
    project=tmp_path/"project"; (project/".prime/agent").mkdir(parents=True); (project/".prime/agent/APPEND_SYSTEM.md").write_text(KERNEL.read_text())
    skill=project/".ralph/skills/oversee-episode/SKILL.md"; skill.parent.mkdir(parents=True); skill.write_text(SKILL.read_text())
    agent=tmp_path/"agent"; agent.mkdir(); records=tmp_path/"records.jsonl"; result=tmp_path/"result.json"
    provider=tmp_path/"provider.ts"
    provider.write_text(rf'''import{{appendFileSync}}from"node:fs";import{{createAssistantMessageEventStream}}from"@earendil-works/pi-ai";const p={json.dumps(str(records))};export default function x(pi){{pi.registerProvider("poc",{{baseUrl:"x",apiKey:"x",api:"poc",streamSimple(model,context){{const all=JSON.stringify(context.messages??[]),tokens=Math.ceil(all.length/4);appendFileSync(p,JSON.stringify({{kernel:context.systemPrompt.split("PRIME_CLAW_CONVERSATION_IDENTITY_V1").length-1,package:all.split("name: oversee-episode").length-1,after:all.includes("AFTER_COMPACTION")}})+"\n");const s=createAssistantMessageEventStream();queueMicrotask(()=>{{const m={{role:"assistant",content:[{{type:"text",text:"ok"}}],api:model.api,provider:model.provider,model:model.id,usage:{{input:tokens,output:1,cacheRead:0,cacheWrite:0,totalTokens:tokens+1,cost:{{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}}}},stopReason:"stop",timestamp:Date.now()}};s.push({{type:"start",partial:m}});s.push({{type:"done",reason:"stop",message:m}});s.end()}});return s}},models:[{{id:"m",name:"M",reasoning:false,input:["text"],cost:{{input:0,output:0,cacheRead:0,cacheWrite:0}},contextWindow:12000,maxTokens:1000}}]}})}}''')
    setup=tmp_path/"setup.ts"
    setup.write_text(rf'''import{{mkdirSync,writeFileSync}}from"node:fs";import{{dirname,join}}from"node:path";export default function s(pi){{pi.on("session_start",(_e,ctx)=>{{const id=ctx.sessionManager.getSessionId(),slug="alpha",sessionFile=join(ctx.cwd,"episode.jsonl"),path=join(ctx.cwd,".prime/agent/state/spec-episodes/alpha.json");mkdirSync(dirname(path),{{recursive:true}});writeFileSync(path,JSON.stringify({{version:2,slug,sourceLocation:".ralph/plans/future/alpha",ownerSessionId:id,episodeId:"episode",episodeActiveSessionId:"active",episodeSessionFile:sessionFile,branch:"episode/alpha",worktree:join(ctx.cwd,"worktree"),sessionName:"alpha-episode",bootstrapAdmission:"delivered"}}));pi.appendEntry("prime-claw-conversation-oversight",{{version:1,status:"active",ownerSessionId:id,sourceLocation:".ralph/plans/future/alpha",slug,episodeId:"episode",episodeSessionFile:sessionFile}})}})}}''')
    driver=tmp_path/"driver.ts"
    driver.write_text(rf'''import{{writeFileSync}}from"node:fs";import{{createAgentSessionServices,createAgentSessionFromServices,SessionManager}}from"@earendil-works/pi-coding-agent";const cwd={json.dumps(str(project))},agentDir={json.dumps(str(agent))},provider={json.dumps(str(provider))},setup={json.dumps(str(setup))},ext={json.dumps(str(EXT))},result={json.dumps(str(result))};export default function d(pi){{pi.on("session_start",async()=>{{let session;try{{const services=await createAgentSessionServices({{cwd,agentDir,noBuiltinHerdrReporter:true,telemetryDisabled:true,resourceLoaderOptions:{{additionalExtensionPaths:[provider,setup,ext],noExtensions:true,noSkills:true,noPromptTemplates:true,noContextFiles:true,noThemes:true}}}});const model=services.modelRegistry.find("poc","m"),made=await createAgentSessionFromServices({{services,sessionManager:SessionManager.inMemory(cwd),model,thinkingLevel:"off",noTools:true,prewarmIpythonKernel:false,telemetryDisabled:true}});session=made.session;await session.bindExtensions({{}});for(let i=0;i<3;i++)await session.prompt("LONG "+"x".repeat(60000));await session.prompt("AFTER_COMPACTION");writeFileSync(result,JSON.stringify({{ok:true}}))}}catch(e){{writeFileSync(result,JSON.stringify({{error:String(e),stack:e?.stack}}))}}finally{{await session?.disposeAsync()}}}})}}''')
    outer=tmp_path/"outer.ts"; _outer_provider(outer)
    cp=subprocess.run([PRIME,"--mode","text","--offline","--no-session","--no-skills","--no-prompt-templates","--no-context-files","--no-extensions","--cwd",str(project),"-e",str(outer),"-e",str(driver),"--provider","outer","--model","m","-p","outer"],cwd=REPO,capture_output=True,text=True,timeout=30)
    assert cp.returncode==0,cp.stdout+cp.stderr
    assert json.loads(result.read_text())=={"ok":True}
    rows=[json.loads(x) for x in records.read_text().splitlines()]
    assert any(r["kernel"]==0 and r["package"]==0 for r in rows)
    after=[r for r in rows if r["after"] and r["kernel"]==1]
    assert after and after[0]["package"]==1
