#!/usr/bin/env python3
"""Generate or verify the checked-in Prime Claw neutral role-kernel constants."""

import argparse
import hashlib
import json
from pathlib import Path
import sys

START = "<!-- prime-claw:role-kernel:start -->"
END = "<!-- prime-claw:role-kernel:end -->"
SENTINEL = "PRIME_CLAW_ROLE_KERNEL_V1"


def load_kernel(path: Path) -> bytes:
    data = path.read_bytes()
    if data.endswith((b"\n", b"\r")):
        raise ValueError("ROLE_KERNEL.md must end at the closing marker without a trailing newline")
    for token in (START.encode(), END.encode(), SENTINEL.encode()):
        if data.count(token) != 1:
            raise ValueError(f"ROLE_KERNEL.md must contain exactly one {token.decode()}")
    if not data.startswith(START.encode()) or not data.endswith(END.encode()):
        raise ValueError("ROLE_KERNEL.md markers must bound the complete file")
    if data.find(START.encode()) >= data.find(END.encode()):
        raise ValueError("ROLE_KERNEL.md markers are reversed")
    data.decode("utf-8")
    return data


def render(data: bytes) -> bytes:
    text = data.decode("utf-8")
    digest = hashlib.sha256(data).hexdigest()
    generated = (
        "/* Generated by scripts/generate-prime-agent-role-kernel.py; do not edit. */\n"
        f"export const PRIME_CLAW_ROLE_KERNEL_START = {json.dumps(START)};\n"
        f"export const PRIME_CLAW_ROLE_KERNEL_END = {json.dumps(END)};\n"
        f"export const PRIME_CLAW_ROLE_KERNEL_SENTINEL = {json.dumps(SENTINEL)};\n"
        f"export const PRIME_CLAW_ROLE_KERNEL_TEXT = {json.dumps(text)};\n"
        f"export const PRIME_CLAW_ROLE_KERNEL_SHA256 = {json.dumps(digest)};\n"
    )
    return generated.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("write", "check"))
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    try:
        expected = render(load_kernel(args.source))
        if args.mode == "write":
            args.destination.parent.mkdir(parents=True, exist_ok=True)
            args.destination.write_bytes(expected)
            return 0
        try:
            actual = args.destination.read_bytes()
        except FileNotFoundError:
            print(f"missing generated role kernel: {args.destination}", file=sys.stderr)
            return 1
        if actual != expected:
            print(f"stale generated role kernel: {args.destination}", file=sys.stderr)
            return 1
        return 0
    except (OSError, UnicodeError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
